"""仓储端口。

application 层通过 :class:`Repositories` 访问持久化，不认识 SQLAlchemy。

不可变对象（ProjectVersion、RunSnapshot）的仓储刻意只有 ``add`` 和读取方法，
没有 ``update``——修改不可变内容必须创建新对象（GR-201、GR-202）。
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ..compute import ComputePlan, ResourceEntitlement
from ..models import (
    Activity,
    Artifact,
    Environment,
    EnvironmentVersion,
    ForkRelation,
    IdempotencyRecord,
    LegacyWorkspace,
    Membership,
    Notification,
    Project,
    ProjectFile,
    ProjectVersion,
    Run,
    RunConfiguration,
    RunEvent,
    SharedResource,
    SharedResourceVersion,
    User,
    UserGroup,
    WorkspaceVariable,
)
from ..pagination import Page, PageRequest
from ..run_snapshot import RunSnapshot


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get(self, user_id: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...


class LegacyWorkspaceRepository(Protocol):
    """Private persistence anchors retained only for #36-#42 compatibility."""

    async def add(self, workspace: LegacyWorkspace) -> None: ...
    async def get(self, workspace_id: str) -> LegacyWorkspace | None: ...
    async def update(self, workspace: LegacyWorkspace) -> None: ...
    async def get_personal(self, owner_id: str) -> LegacyWorkspace | None: ...


class UserGroupRepository(Protocol):
    async def add(self, user_group: UserGroup) -> None: ...
    async def get(self, user_group_id: str) -> UserGroup | None: ...
    async def get_for_update(self, user_group_id: str) -> UserGroup | None: ...
    async def get_for_active_member(self, user_group_id: str, user_id: str) -> UserGroup | None: ...
    async def update(self, user_group: UserGroup) -> None: ...
    async def list_for_user(self, user_id: str) -> list[UserGroup]: ...


class MembershipRepository(Protocol):
    async def add(self, membership: Membership) -> None: ...
    async def update(self, membership: Membership) -> None: ...
    async def get(self, user_group_id: str, user_id: str) -> Membership | None: ...
    async def list_for_user_group(self, user_group_id: str) -> list[Membership]: ...
    async def list_pending_for_user(self, user_id: str) -> list[Membership]: ...
    async def get_active_owner(self, user_group_id: str) -> Membership | None: ...


class VariableRepository(Protocol):
    async def list_for_workspace(self, workspace_id: str) -> list[WorkspaceVariable]: ...
    async def upsert(self, variable: WorkspaceVariable) -> None: ...
    async def delete(self, workspace_id: str, name: str) -> None: ...


class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...
    async def get(self, project_id: str) -> Project | None: ...
    async def update(self, project: Project) -> None: ...
    async def list_for_workspace(self, workspace_id: str, page: PageRequest) -> Page[Project]: ...
    async def list_discoverable_for_user(
        self, user_id: str, page: PageRequest
    ) -> Page[Project]: ...
    async def list_for_user(self, user_id: str, *, limit: int) -> list[Project]:
        """按最近更新时间列出用户可见的 Project，用于个人首页。"""
        ...

    async def name_exists(self, workspace_id: str, name: str) -> bool: ...


class ProjectFileRepository(Protocol):
    async def list_for_project(self, project_id: str) -> list[ProjectFile]: ...
    async def get(self, project_id: str, path: str) -> ProjectFile | None: ...
    async def upsert(self, file: ProjectFile) -> None: ...
    async def delete(self, project_id: str, path: str) -> None: ...
    async def delete_under(self, project_id: str, prefix: str) -> int:
        """删除某个目录前缀下的全部文件，返回删除数量。"""
        ...


class ProjectVersionRepository(Protocol):
    async def add(self, version: ProjectVersion) -> None: ...
    async def get(self, version_id: str) -> ProjectVersion | None: ...
    async def list_for_project(
        self, project_id: str, page: PageRequest
    ) -> Page[ProjectVersion]: ...
    async def latest(self, project_id: str) -> ProjectVersion | None: ...
    async def next_sequence(self, project_id: str) -> int: ...


class EnvironmentRepository(Protocol):
    async def list_environments(self) -> list[Environment]: ...
    async def get_environment(self, environment_id: str) -> Environment | None: ...
    async def list_versions(self, environment_id: str) -> list[EnvironmentVersion]: ...
    async def get_version(self, version_id: str) -> EnvironmentVersion | None: ...


class ComputePlanRepository(Protocol):
    async def list_all(self) -> list[ComputePlan]: ...
    async def get(self, plan_id: str) -> ComputePlan | None: ...


class EntitlementRepository(Protocol):
    async def list_for_workspace(self, workspace_id: str) -> list[ResourceEntitlement]: ...
    async def get_for_plan(
        self, workspace_id: str, compute_plan_id: str
    ) -> ResourceEntitlement | None: ...
    async def add(self, entitlement: ResourceEntitlement) -> None: ...

    async def lock_for_plan(
        self, workspace_id: str, compute_plan_id: str
    ) -> ResourceEntitlement | None:
        """取权益并在当前事务内独占它，直到事务结束。

        用于把「数一数还剩几个并发名额，然后创建 Run」这一段串行化。
        不加锁的话两个请求会同时读到「还没到上限」，然后都创建成功——
        并发上限就形同虚设了。
        """
        ...


class RunConfigurationRepository(Protocol):
    async def add(self, configuration: RunConfiguration) -> None: ...
    async def get(self, configuration_id: str) -> RunConfiguration | None: ...
    async def update(self, configuration: RunConfiguration) -> None: ...
    async def delete(self, configuration_id: str) -> None: ...
    async def list_for_project(self, project_id: str) -> list[RunConfiguration]: ...


class RunSnapshotRepository(Protocol):
    """不可变对象仓储：只有写入和读取，没有 update。"""

    async def add(self, snapshot: RunSnapshot) -> None: ...
    async def get(self, snapshot_id: str) -> RunSnapshot | None: ...


class RunRepository(Protocol):
    async def add(self, run: Run) -> None: ...
    async def get(self, run_id: str) -> Run | None: ...
    async def update(self, run: Run) -> None: ...
    async def list_for_project(self, project_id: str, page: PageRequest) -> Page[Run]: ...
    async def list_for_user(self, user_id: str, *, limit: int) -> list[Run]: ...
    async def list_unfinished(self) -> list[Run]:
        """列出所有未进入终态的 Run，供状态同步使用。"""
        ...

    async def claim_terminal(self, run: Run) -> bool:
        """条件更新把 Run 推进到终态。抢到返回 True，别人已推进过返回 False。"""
        ...

    async def count_unfinished_for_plan(self, workspace_id: str, compute_plan_id: str) -> int: ...


class IdempotencyRepository(Protocol):
    """幂等登记。

    ``reserve`` 必须在真正产生副作用（提交调度任务）之前调用并落库，
    否则并发的第二个请求会先把作业提交出去，再因为冲突回滚——
    数据库干净了，但集群上已经多跑了一个作业。
    """

    async def find(self, workspace_id: str, key: str) -> IdempotencyRecord | None: ...
    async def reserve(self, workspace_id: str, key: str, endpoint: str) -> None: ...
    async def attach_run(self, workspace_id: str, key: str, run_id: str) -> None: ...


class RunEventRepository(Protocol):
    async def add(self, event: RunEvent) -> None: ...
    async def list_for_run(self, run_id: str) -> list[RunEvent]: ...


class ArtifactRepository(Protocol):
    async def add(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: str) -> Artifact | None: ...
    async def update(self, artifact: Artifact) -> None: ...
    async def list_for_run(self, run_id: str) -> list[Artifact]: ...


class ActivityRepository(Protocol):
    async def add(self, activity: Activity) -> None: ...
    async def list_for_workspace(self, workspace_id: str, page: PageRequest) -> Page[Activity]: ...
    async def list_for_project(self, project_id: str, page: PageRequest) -> Page[Activity]: ...


class NotificationRepository(Protocol):
    """通知按**收件人**查，不按 Workspace 查。

    被移除的成员已经看不到那个 Workspace 了，但「你被移除了」这条通知
    必须还能读到——按 Workspace 过滤会把它一起挡掉。
    """

    async def add(self, notification: Notification) -> None: ...
    async def list_for_user(
        self, user_id: str, page: PageRequest, *, unread_only: bool = False
    ) -> Page[Notification]: ...
    async def count_unread(self, user_id: str) -> int: ...
    async def mark_read(self, user_id: str, notification_id: str, at: datetime) -> bool:
        """标记已读。返回 False 表示这条通知不属于这个人或不存在。"""
        ...

    async def mark_all_read(self, user_id: str, at: datetime) -> int: ...


class ForkRelationRepository(Protocol):
    """一个 Project 最多一条来源记录，所以按 project_id 查就够了。"""

    async def add(self, relation: ForkRelation) -> None: ...
    async def get_for_project(self, project_id: str) -> ForkRelation | None: ...


class SharedResourceRepository(Protocol):
    """Shared Resource 与版本的仓储。

    可见性按设计稿 §2.6 / §3.2.1 分两层：
    ``owner_workspace_id IS NULL`` 是 Platform 资源，全平台可见；
    否则归 Workspace，对其成员可见。跨 Workspace Asset Grant 在 M4 单独 Issue，
    这里不提供按 grant 过滤的查询。

    版本不可变（GR-201）：只有 ``add`` 和读取方法，没有 ``update``。
    """

    async def add(self, resource: SharedResource) -> None: ...
    async def get(self, resource_id: str) -> SharedResource | None: ...
    async def update(self, resource: SharedResource) -> None: ...
    async def list_platform(self) -> list[SharedResource]:
        """Platform 持有的资源（``owner_workspace_id IS NULL``）。"""
        ...

    async def list_for_workspace(self, workspace_id: str) -> list[SharedResource]: ...

    async def add_version(self, version: SharedResourceVersion) -> None: ...
    async def get_version(self, version_id: str) -> SharedResourceVersion | None: ...
    async def list_versions(self, resource_id: str) -> list[SharedResourceVersion]: ...
    async def latest_version(self, resource_id: str) -> SharedResourceVersion | None: ...
    async def next_version_sequence(self, resource_id: str) -> int: ...


class Repositories(Protocol):
    """一次工作单元内可用的全部仓储。"""

    users: UserRepository
    legacy_workspaces: LegacyWorkspaceRepository
    user_groups: UserGroupRepository
    memberships: MembershipRepository
    variables: VariableRepository
    projects: ProjectRepository
    project_files: ProjectFileRepository
    project_versions: ProjectVersionRepository
    environments: EnvironmentRepository
    compute_plans: ComputePlanRepository
    entitlements: EntitlementRepository
    run_configurations: RunConfigurationRepository
    run_snapshots: RunSnapshotRepository
    runs: RunRepository
    run_events: RunEventRepository
    idempotency: IdempotencyRepository
    artifacts: ArtifactRepository
    activities: ActivityRepository
    notifications: NotificationRepository
    fork_relations: ForkRelationRepository
    shared_resources: SharedResourceRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

    async def ping(self) -> None:
        """确认存储真的可用。不可用时抛异常。

        用于就绪探针：进程活着不等于依赖都通，两者要分开回答。
        """
        ...
