export const authCopy = {
  login: '统一身份认证登录',
  logout: '退出登录',
  profile: '个人资料',
  settings: '设置',
  userMenu: (name: string) => `当前用户 ${name}`,
  confirming: '正在确认登录状态…',
  confirmFailed: '无法确认登录状态。',
  confirmFailedNext: '请检查网络连接后重试。',
  retry: '重试',
  publicTitle: '107 Workspace',
  publicSubtitle: '登录后进入 Project，配置运行方案并提交计算作业。',
  publicLead:
    '面向中国科学技术大学 107 算力平台的协作式计算工作空间。登录后进入 Project，配置运行方案并提交计算作业。',
  publicAudience: '统一身份认证面向科大用户。',
  publicNotesTitle: '登录说明：',
  publicNotes: [
    '学校用户请使用统一身份认证。',
    '账密登录是普通登录方法，用于受信任演示中已配置的管理员账号。',
    '不提供自助注册；账号由学校身份或平台配置产生。',
  ],
  orSignInWith: '或使用以下方式登录',
  showPassword: '显示密码',
  hidePassword: '隐藏密码',
  publicFooter: '107 Workspace',
  passwordLogin: '账密登录',
  username: '用户名',
  password: '密码',
  passwordSubmit: '登录',
  passwordLoginFailed: '登录失败，请检查用户名和密码。',
} as const
