"""建立核心运行闭环数据结构。

Revision ID: c5f26be2085b
Revises:
Create Date: 2026-07-26 17:09:19.426801
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c5f26be2085b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compute_plans",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_nodes", sa.Integer(), nullable=False),
        sa.Column("default_cpus", sa.Integer(), nullable=False),
        sa.Column("default_memory_mb", sa.Integer(), nullable=False),
        sa.Column("default_gpus", sa.Integer(), nullable=False),
        sa.Column("default_time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("max_nodes", sa.Integer(), nullable=False),
        sa.Column("max_cpus", sa.Integer(), nullable=False),
        sa.Column("max_memory_mb", sa.Integer(), nullable=False),
        sa.Column("max_gpus", sa.Integer(), nullable=False),
        sa.Column("max_time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("cluster", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("partition", sa.String(length=64), nullable=False),
        sa.Column("qos", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "environments",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_workspace_id", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run_snapshots",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "environment_versions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("environment_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.Column("setup_command", sa.Text(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("environment_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_environment_versions_environment_id"), ["environment_id"], unique=False
        )

    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("default_environment_version_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspaces_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_workspaces_owner_kind", ["owner_id", "kind"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_membership"),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memberships_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("environment_version_id", sa.String(length=40), nullable=True),
        sa.Column("default_run_configuration_id", sa.String(length=40), nullable=True),
        sa.Column("created_by", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_project_name"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projects_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "resource_entitlements",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("compute_plan_id", sa.String(length=40), nullable=False),
        sa.Column("max_concurrent_runs", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["compute_plan_id"],
            ["compute_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "compute_plan_id", name="uq_entitlement"),
    )
    with op.batch_alter_table("resource_entitlements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_entitlements_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_secrets",
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "name"),
    )
    op.create_table(
        "workspace_variables",
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "name"),
    )
    op.create_table(
        "project_files",
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "path"),
    )
    op.create_table(
        "project_versions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "sequence", name="uq_version_sequence"),
    )
    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_versions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "run_configurations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("working_directory", sa.String(length=1024), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("environment_version_id", sa.String(length=40), nullable=True),
        sa.Column("environment_variables", sa.JSON(), nullable=False),
        sa.Column("input_bindings", sa.JSON(), nullable=False),
        sa.Column("compute_plan_id", sa.String(length=40), nullable=False),
        sa.Column("compute_request", sa.JSON(), nullable=True),
        sa.Column("artifact_rules", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_configurations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_run_configurations_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("snapshot_id", sa.String(length=40), nullable=False),
        sa.Column("source_run_configuration_id", sa.String(length=40), nullable=True),
        sa.Column("source_run_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduler_job_id", sa.String(length=128), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["run_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_created_by"), ["created_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_artifacts_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "project_version_files",
        sa.Column("version_id", sa.String(length=40), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
        ),
        sa.PrimaryKeyConstraint("version_id", "path"),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_events_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_events_run_id"))

    op.drop_table("run_events")
    op.drop_table("project_version_files")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_run_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_project_id"))

    op.drop_table("artifacts")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_project_id"))
        batch_op.drop_index(batch_op.f("ix_runs_created_by"))

    op.drop_table("runs")
    with op.batch_alter_table("run_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_configurations_project_id"))

    op.drop_table("run_configurations")
    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_versions_project_id"))

    op.drop_table("project_versions")
    op.drop_table("project_files")
    op.drop_table("workspace_variables")
    op.drop_table("workspace_secrets")
    with op.batch_alter_table("resource_entitlements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_entitlements_workspace_id"))

    op.drop_table("resource_entitlements")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_workspace_id"))

    op.drop_table("projects")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_index("ix_workspaces_owner_kind")
        batch_op.drop_index(batch_op.f("ix_workspaces_owner_id"))

    op.drop_table("workspaces")
    with op.batch_alter_table("environment_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_environment_versions_environment_id"))

    op.drop_table("environment_versions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("run_snapshots")
    op.drop_table("environments")
    op.drop_table("compute_plans")
    # ### end Alembic commands ###
